; ---------------------------------------------------------------
; opcodes.inc
; AnotherX16 - Commander X16 port of Another World
; ---------------------------------------------------------------

.global opcode_00_SETI, opcode_01_MOV, opcode_02_ADD, opcode_03_ADDC, opcode_04_CALL, opcode_05_RET, opcode_06_YIELD
.global opcode_07_JMP, opcode_08_SETVEC, opcode_09_DJNZ, opcode_0A_CJMP, opcode_0B_SETPAL, opcode_0C_CCTRL
.global opcode_0D_SELECTP, opcode_0E_FILLP, opcode_0F_COPYP, opcode_10_BLITP, opcode_11_KILL, opcode_12_DTEXT
.global opcode_13_SUB, opcode_14_AND, opcode_15_OR, opcode_16_SHL, opcode_17_SHR, opcode_18_SOUND, opcode_19_LOAD
.global opcode_1A_MUSIC